zineman/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_user import UserMixin

db = SQLAlchemy()
session = db.session


def get_or_create(session, model, **kwargs):
    instance = model.query.filter_by(**kwargs).first()
    if not instance:
        instance = model(**kwargs)
        session.add(instance)
    return instance


class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), nullable=False)
    email = db.Column(db.String(255, collation='NOCASE'), nullable=False, unique=True)
    email_confirmed_at = db.Column(db.DateTime())
    password = db.Column(db.String(255), nullable=False, server_default='')
    # token = db.Column(db.String(255))
    active = db.Column('is_active', db.Boolean(), nullable=False, server_default='1')
    roles = db.relationship('Role', secondary='users_roles')

    def has_role(self, role):
        return any([r.name == role for r in self.roles])

    def __repr__(self):
        return self.name


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), nullable=False, unique=True)

    def __repr__(self):
        return self.name


class UserRoles(db.Model):
    __tablename__ = 'users_roles'
    id = db.Column(db.Integer(), primary_key=True)
    user_id = db.Column(db.Integer(), db.ForeignKey('users.id', ondelete='CASCADE'))
    role_id = db.Column(db.Integer(), db.ForeignKey('roles.id', ondelete='CASCADE'))


class Volume(db.Model):
    __tablename__ = 'volumes'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), nullable=False)
    release = db.Column(db.Date, nullable=False)

    def __repr__(self):
        return self.name


class Subscription(db.Model):
    __tablename__ = 'subscriptions'
    id = db.Column(db.Integer, primary_key=True)
    is_active = db.Column(db.Boolean, nullable=False, default=False)
    start_date = db.Column(db.Date, nullable=False)
    end_date = db.Column(db.Date, nullable=False)

    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    user = db.relationship('User', backref=db.backref('subscriptions'))

    def __repr__(self):
        return '{}: {} to {}'.format(self.user.name, self.start_date, self.end_date)


class Page(db.Model):
    __tablename__ = 'pages'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), nullable=False)
    slug = db.Column(db.String(255), nullable=False)
    body = db.Column(db.Text)
    weight = db.Column(db.Integer, default=0)

    def __repr__(self):
        return self.title

zineman/__init__.py
__version__ = '0.1'

zineman/app.py
from datetime import datetime

from flask import Flask
from flask_admin.menu import MenuLink
from flask_user import UserManager

from zineman.admin import admin
from zineman.config import config_from_file
from zineman.models import User, Role, db, get_or_create
from zineman.views.main import main


def _setup_db(app):
    # Create the tables
    db.create_all()
    # Create the roles
    subscriber_role = get_or_create(db.session, Role, name='subscriber')
    superuser_role = get_or_create(db.session, Role, name='superuser')
    # Optionally create a superuser
    if app.config.get('ZINEMAN_SUPERUSER', None):
        superuser = app.config['ZINEMAN_SUPERUSER']
        if not User.query.filter(User.email == superuser['email']).first():
            user = User(
                name=superuser.get('name', 'Superuser'),
                email=superuser['email'],
                email_confirmed_at=datetime.utcnow(),
                password=app.user_manager.hash_password(superuser.get('password', 'Password1')),
                active=True
            )
            user.roles.extend([subscriber_role, superuser_role])
            db.session.add(user)
    db.session.commit()


def create_app():
    app = Flask('zineman')
    config_from_file(app, 'zineman.conf')
    db.init_app(app)
    admin.init_app(app)
    UserManager(app, db, User)
    # Register blueprints
    app.register_blueprint(main)
    with app.app_context():
        _setup_db(app)
        # Set up menu shortcuts
        admin.add_link(MenuLink('Back to main site', '/'))
        admin.add_link(MenuLink('Logout', '/user/sign-out'))
    return app

zineman/views/main.py
from flask import Blueprint, render_template

from zineman.models import Page


main = Blueprint('main', __name__)


@main.route('/', methods=['GET'])
def index():
    pages = Page.query.all()
    return render_template('index.html', pages=pages)


@main.route('/pages/<slug>', methods=['GET'])
def pages(slug):
    page = Page.query.filter_by(slug=slug).first()
    pages = Page.query.all()
    return render_template('page.html', page=page, pages=pages)

zineman/templates/base.html
{% import 'admin/layout.html' as layout with context -%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% if page %}{{ page.title }} | {% endif %}{{config.get('ZINEMAN_TITLE', 'ZineMan')}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/cosmo/bootstrap.min.css" rel="stylesheet" integrity="sha384-uhut8PejFZO8994oEgm/ZfAv0mW1/b83nczZzSwElbeILxwkN491YQXsCFTE6+nx" crossorigin="anonymous">
    <style>
      section.main {
        margin-top: 74px;
      }
    </style>
  </head>
  <body>
    <div class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
      <div class="container">
        <a href="../" class="navbar-brand">The Scooter Zine</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          {% if pages %}
          <ul class="navbar-nav">
            {% for page in pages %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.pages', slug=page.slug) }}">{{ page.title }}</a>
            </li>
            {% endfor %}
          </ul>
          {% endif %}
          <ul class="nav navbar-nav ml-auto">
            {% if current_user.is_authenticated  and current_user.has_role('superuser') %}
            <li class="nav-item">
              <a class="nav-link" href="/admin/">Admin</a>
            </li>
            {% endif %}
            <li class="nav-item">
              {% if current_user.is_authenticated %}
              <a class="nav-link" href="{{ url_for('user.logout') }}">Log out</a>
              {% else %}
              <a class="nav-link" href="{{ url_for('user.login') }}">Log in</a>
              {% endif %}
            </li>
          </ul>
        </div>
      </div>
    </div>
    <section class="main container">
{% block messages %}
{{ layout.messages() }}
{% endblock %}
{% block content %}{% endblock %}
      <footer id="footer">
        <div class="row">
          <div class="col-lg-12">
            <ul class="list-unstyled">
              <li class="float-lg-right"><a href="#top">Back to top</a></li>
              <li><a href="https://blog.bootswatch.com" onclick="pageTracker._link(this.href); return false;">Blog</a></li>
              <li><a href="https://blog.bootswatch.com/rss/">RSS</a></li>
              <li><a href="https://twitter.com/bootswatch">Twitter</a></li>
              <li><a href="https://github.com/thomaspark/bootswatch/">GitHub</a></li>
              <li><a href="../help/#api">API</a></li>
              <li><a href="../help/#donate">Donate</a></li>
            </ul>
            <p>Made by <a href="https://thomaspark.co">Thomas Park</a>.</p>
            <p>Code released under the <a href="https://github.com/thomaspark/bootswatch/blob/master/LICENSE">MIT License</a>.</p>
            <p>Based on <a href="https://getbootstrap.com" rel="nofollow">Bootstrap</a>. Icons from <a href="https://fontawesome.com/" rel="nofollow">Font Awesome</a>. Web fonts from <a href="https://fonts.google.com/" rel="nofollow">Google</a>.</p>
          </div>
        </div>
      </footer>
    </section>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

zineman/templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Hello world</h1>
{% endblock %}

zineman/templates/page.html
{% extends 'base.html' %}
{% block content %}
{{ page.body | safe }}
{% endblock %}

zineman/templates/settings.html
{% extends 'admin/master.html' %}
{% block content %}
<h1>Settings</h1>
{% endblock %}